micronaut:
  application:
    name: gameServiceKotlin

netty:
  default:
    allocator:
      max-order: 3

datasources:
  default:
    url: 'jdbc:postgresql://localhost:5432/game_service'
    username: 'game_service'
    password: 's3cr3t'
    driverClassName: 'org.postgresql.Driver'

jpa:
  default:
    packages-to-scan:
      - 'dev.oxeg.gameservice'
    properties:
      hibernate:
        hbm2ddl:
          auto: none
        show_sql: true

flyway:
  datasources:
    default:
      enabled: true
